export const COLOR_BUTTON_PRIMARY = '#0A0E39'
export const COLOR_BUTTON_PRIMARY_HOVER = '#5B2C6F'

export const COLOR_BACKGRAUND_NAVBAR = '#0A0E39'
export const COLOR_BACKGRAUND_SECCTION = '#E5E5EA'
export const COLOR_BACKGRAUND_CARD = '#FCFCFC'
