export const COLOR_PRIMARY = '#080928'
export const COLOR_SECONDARY = '#4EFFF7'
export const COLOR_BACKGROUND = '#0F294A'
export const COLOR_PINK = '#CE2BFE'
export const COLOR_PURPURE = '#9352EE'
export const COLOR_CYAN = '#46DFFF'
